<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="PBNHMRY"><DocLocation><![CDATA[C:\Users\darapch\Desktop\InfoPro_Residence_Modifications\TestScript\BIGDS031_ServiceRecording]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[BIGDS031_ServiceRecording]]></DName>
<Res><![CDATA[Res20]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:29]]></Time>
<TimeTick>1488532469</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:29]]></Time>
<TimeTick>1488532469</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:29]]></Time>
<TimeTick>1488532469</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:29]]></Time>
<TimeTick>1488532469</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ field1439(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:29]]></Time>
<TimeTick>1488532469</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" >
<Disp><![CDATA[[ field1439(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:29]]></Time>
<TimeTick>1488532469</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="15" >
<Disp><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:31]]></Time>
<TimeTick>1488532471</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:31]]></Time>
<TimeTick>1488532471</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ field1439(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:31]]></Time>
<TimeTick>1488532471</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" >
<Disp><![CDATA[[ field1439(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:31]]></Time>
<TimeTick>1488532471</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="22" >
<Disp><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:32]]></Time>
<TimeTick>1488532472</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:32]]></Time>
<TimeTick>1488532472</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ field1439(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:32]]></Time>
<TimeTick>1488532472</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" >
<Disp><![CDATA[[ field1439(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:32]]></Time>
<TimeTick>1488532472</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" >
<Disp><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:33]]></Time>
<TimeTick>1488532473</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:33]]></Time>
<TimeTick>1488532473</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ field1439(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:33]]></Time>
<TimeTick>1488532473</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="34" >
<Disp><![CDATA[[ field1439(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:33]]></Time>
<TimeTick>1488532473</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="36" >
<Disp><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:35]]></Time>
<TimeTick>1488532475</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="38" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:35]]></Time>
<TimeTick>1488532475</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="40" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ field1439(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:35]]></Time>
<TimeTick>1488532475</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="41" >
<Disp><![CDATA[[ field1439(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:35]]></Time>
<TimeTick>1488532475</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="43" >
<Disp><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:36]]></Time>
<TimeTick>1488532476</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="45" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:36]]></Time>
<TimeTick>1488532476</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/3/2017 - 14:44:37]]></Time>
<TimeTick>1488532477</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="49" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/3/2017 - 14:44:26" eTime="3/3/2017 - 14:44:39" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="3/3/2017 - 14:44:25" eTime="3/3/2017 - 14:44:39" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test BIGDS031_ServiceRecording Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>