<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="PBNHMRY"><DocLocation><![CDATA[C:\Users\darapch\Desktop\InfoPro_Residence_Modifications\TestScript\Driver_TestSuit]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Driver_TestSuit]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:19]]></Time>
<TimeTick>1490603839</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="7" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:19]]></Time>
<TimeTick>1490603839</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:19]]></Time>
<TimeTick>1490603839</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[Action1 [Driver_Repaired]]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[StartRun]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "StartRun" started.]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:20]]></Time>
<TimeTick>1490603840</TimeTick>
<NodeArgs eType="Transaction" icon="6" nRep="11" nType="Start Transaction" >
<Disp><![CDATA[StartRun]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:20]]></Time>
<TimeTick>1490603840</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="12" status="Passed" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:20]]></Time>
<TimeTick>1490603840</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="13" status="Passed" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:20]]></Time>
<TimeTick>1490603840</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="14" status="Passed" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[START RUN]]></Obj>
<Details ><![CDATA[3/27/2017 2:07:20 PM]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:20]]></Time>
<TimeTick>1490603840</TimeTick>
<NodeArgs eType="User" icon="7" nRep="15" >
<Disp><![CDATA[START RUN]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Excel file loaded sucessfully]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:20]]></Time>
<TimeTick>1490603840</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" >
<Disp><![CDATA[Excel file loaded sucessfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Infopro Application opened successfully]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:25]]></Time>
<TimeTick>1490603845</TimeTick>
<NodeArgs eType="User" icon="7" nRep="17" status="Passed" >
<Disp><![CDATA[Infopro Application opened successfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Configure PC5250]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:30]]></Time>
<TimeTick>1490603850</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Configure PC5250.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:30]]></Time>
<TimeTick>1490603850</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[Configure PC5250.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Configure PC5250.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:30]]></Time>
<TimeTick>1490603850</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" >
<Disp><![CDATA[Configure PC5250.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[SystemName.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["SYS01"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:30]]></Time>
<TimeTick>1490603850</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" >
<Disp><![CDATA[SystemName.SetText]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="18" >
<Disp><![CDATA[Configure PC5250]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[System i signon]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:30]]></Time>
<TimeTick>1490603850</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[System i signon.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:30]]></Time>
<TimeTick>1490603850</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" >
<Disp><![CDATA[System i signon.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[System i signon.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:31]]></Time>
<TimeTick>1490603851</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" >
<Disp><![CDATA[System i signon.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="23" >
<Disp><![CDATA[System i signon]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:35]]></Time>
<TimeTick>1490603855</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:35]]></Time>
<TimeTick>1490603855</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[UserId.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:35]]></Time>
<TimeTick>1490603855</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="29" >
<Disp><![CDATA[UserId.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[  [24 x 80] ].Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:35]]></Time>
<TimeTick>1490603855</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="31" >
<Disp><![CDATA[[  [24 x 80] ].Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[UserId.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:35]]></Time>
<TimeTick>1490603855</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="32" >
<Disp><![CDATA[UserId.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:35]]></Time>
<TimeTick>1490603855</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="33" >
<Disp><![CDATA[Password.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[UserId.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["darapch"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:35]]></Time>
<TimeTick>1490603855</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="35" >
<Disp><![CDATA[UserId.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="28" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="27" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Enter UserId in the Login Screen]]></Obj>
<Details ><![CDATA[The value 'darapch' entered into the field UserId]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:37]]></Time>
<TimeTick>1490603857</TimeTick>
<NodeArgs eType="User" icon="7" nRep="36" status="Passed" >
<Disp><![CDATA[Enter UserId in the Login Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:37]]></Time>
<TimeTick>1490603857</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:37]]></Time>
<TimeTick>1490603857</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Sachin8187"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:37]]></Time>
<TimeTick>1490603857</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="40" >
<Disp><![CDATA[Password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="39" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:39]]></Time>
<TimeTick>1490603859</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ screen10365 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:39]]></Time>
<TimeTick>1490603859</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="43" >
<Disp><![CDATA[[ screen10365 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ TeScreen ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:39]]></Time>
<TimeTick>1490603859</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="44" >
<Disp><![CDATA[[ TeScreen ].Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="42" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Menu]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:42]]></Time>
<TimeTick>1490603862</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[InfoPro.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:42]]></Time>
<TimeTick>1490603862</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="48" >
<Disp><![CDATA[InfoPro.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="47" >
<Disp><![CDATA[Menu]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="38" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[Enter InfoPro in the Menu Screen]]></Obj>
<Details ><![CDATA[The value '1' entered into the field InfoPro]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:42]]></Time>
<TimeTick>1490603862</TimeTick>
<NodeArgs eType="User" icon="7" nRep="49" status="Passed" >
<Disp><![CDATA[Enter InfoPro in the Menu Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:42]]></Time>
<TimeTick>1490603862</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:42]]></Time>
<TimeTick>1490603862</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:42]]></Time>
<TimeTick>1490603862</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="53" >
<Disp><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ TeScreen ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:42]]></Time>
<TimeTick>1490603862</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="54" >
<Disp><![CDATA[[ TeScreen ].Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="52" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Region]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:43]]></Time>
<TimeTick>1490603863</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Region.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:43]]></Time>
<TimeTick>1490603863</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="57" >
<Disp><![CDATA[Region.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Region.SetCursorPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:43]]></Time>
<TimeTick>1490603863</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="59" >
<Disp><![CDATA[Region.SetCursorPos]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="56" >
<Disp><![CDATA[Region]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:43]]></Time>
<TimeTick>1490603863</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_BACKTAB"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:43]]></Time>
<TimeTick>1490603863</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="62" >
<Disp><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:44]]></Time>
<TimeTick>1490603864</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="64" >
<Disp><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:46]]></Time>
<TimeTick>1490603866</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="66" >
<Disp><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ TeScreen ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:46]]></Time>
<TimeTick>1490603866</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="67" >
<Disp><![CDATA[[ TeScreen ].Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="61" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="51" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Region Selected sucessfully]]></Obj>
<Details ><![CDATA[The Selected Region : BIDBFE]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:48]]></Time>
<TimeTick>1490603868</TimeTick>
<NodeArgs eType="User" icon="7" nRep="69" status="Passed" >
<Disp><![CDATA[Region Selected sucessfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Division]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Division.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="73" >
<Disp><![CDATA[Division.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Nextpage.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="74" >
<Disp><![CDATA[Nextpage.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="72" >
<Disp><![CDATA[Division]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ 3/27/17 1:37:46 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="77" >
<Disp><![CDATA[[ 3/27/17 1:37:46 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="76" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Division]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Division.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="79" >
<Disp><![CDATA[Division.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Division.SetCursorPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="81" >
<Disp><![CDATA[Division.SetCursorPos]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="78" >
<Disp><![CDATA[Division]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ 3/27/17 1:37:46 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_BACKTAB"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="84" >
<Disp><![CDATA[[ 3/27/17 1:37:46 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ 3/27/17 1:37:46 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:53]]></Time>
<TimeTick>1490603873</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="86" >
<Disp><![CDATA[[ 3/27/17 1:37:46 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ 3/27/17 1:37:46 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:55]]></Time>
<TimeTick>1490603875</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="88" >
<Disp><![CDATA[[ 3/27/17 1:37:46 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ TeScreen ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:56]]></Time>
<TimeTick>1490603876</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="89" >
<Disp><![CDATA[[ TeScreen ].Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="83" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="71" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA[Division Selected sucessfully]]></Obj>
<Details ><![CDATA[The Selected Division : 902]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:57]]></Time>
<TimeTick>1490603877</TimeTick>
<NodeArgs eType="User" icon="7" nRep="91" status="Passed" >
<Disp><![CDATA[Division Selected sucessfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:57]]></Time>
<TimeTick>1490603877</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:57]]></Time>
<TimeTick>1490603877</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ Customer(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:57]]></Time>
<TimeTick>1490603877</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="94" >
<Disp><![CDATA[[ Customer(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ Customer(protected) ].SetCursorPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:58]]></Time>
<TimeTick>1490603878</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="96" >
<Disp><![CDATA[[ Customer(protected) ].SetCursorPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ 3/27/17 1:37:56 INFOPRO ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_BACKTAB"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:59]]></Time>
<TimeTick>1490603879</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="98" >
<Disp><![CDATA[[ 3/27/17 1:37:56 INFOPRO ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ 3/27/17 1:37:56 INFOPRO ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:59]]></Time>
<TimeTick>1490603879</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="100" >
<Disp><![CDATA[[ 3/27/17 1:37:56 INFOPRO ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ 3/27/17 1:37:56 INFOPRO ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:59]]></Time>
<TimeTick>1490603879</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="102" >
<Disp><![CDATA[[ 3/27/17 1:37:56 INFOPRO ].SendKey]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="93" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="92" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj ><![CDATA[Select the Primary Option 'Customer Maintenance']]></Obj>
<Details ><![CDATA[The Primary Option 'Customer Maintenance' has been selected]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:59]]></Time>
<TimeTick>1490603879</TimeTick>
<NodeArgs eType="User" icon="7" nRep="103" status="Passed" >
<Disp><![CDATA[Select the Primary Option 'Customer Maintenance']]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:59]]></Time>
<TimeTick>1490603879</TimeTick>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:59]]></Time>
<TimeTick>1490603879</TimeTick>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[[ Maintain(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/27/2017 - 14:07:59]]></Time>
<TimeTick>1490603879</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="106" >
<Disp><![CDATA[[ Maintain(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[[ Maintain(protected) ].SetCursorPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[3/27/2017 - 14:08:00]]></Time>
<TimeTick>1490603880</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="108" >
<Disp><![CDATA[[ Maintain(protected) ].SetCursorPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T79">