<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="PBNHMRY"><DocLocation><![CDATA[C:\Users\darapch\Desktop\InfoPro_Residence_Just Hod For a While\TestScript\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="40" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
Java, Mobile, Oracle, VisualAge, Web, WPF.]]></Details>
<Time><![CDATA[2/15/2017 - 14:23:58]]></Time>
<TimeTick>1487148838</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj ><![CDATA[START RUN]]></Obj>
<Details ><![CDATA[2/15/2017 2:23:59 PM]]></Details>
<Time><![CDATA[2/15/2017 - 14:23:59]]></Time>
<TimeTick>1487148839</TimeTick>
<NodeArgs eType="User" icon="42" nRep="8" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[START RUN]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[Excel file loaded sucessfully]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2/15/2017 - 14:23:59]]></Time>
<TimeTick>1487148839</TimeTick>
<NodeArgs eType="User" icon="42" nRep="9" status="Passed" >
<Disp><![CDATA[Excel file loaded sucessfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[Infopro Application opened successfully]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:10]]></Time>
<TimeTick>1487148850</TimeTick>
<NodeArgs eType="User" icon="42" nRep="10" status="Passed" >
<Disp><![CDATA[Infopro Application opened successfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Configure PC5250]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:15]]></Time>
<TimeTick>1487148855</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Configure PC5250.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:15]]></Time>
<TimeTick>1487148855</TimeTick>
<NodeArgs eType="Replay" icon="43" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Configure PC5250.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Configure PC5250.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:15]]></Time>
<TimeTick>1487148855</TimeTick>
<NodeArgs eType="Replay" icon="43" nRep="13" >
<Disp><![CDATA[Configure PC5250.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SystemName.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["SYS01"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:16]]></Time>
<TimeTick>1487148856</TimeTick>
<NodeArgs eType="Replay" icon="44" nRep="15" >
<Disp><![CDATA[SystemName.SetText]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="43" nRep="11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Configure PC5250]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[System i signon]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:17]]></Time>
<TimeTick>1487148857</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[System i signon.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:17]]></Time>
<TimeTick>1487148857</TimeTick>
<NodeArgs eType="Replay" icon="43" nRep="17" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[System i signon.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[System i signon.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:17]]></Time>
<TimeTick>1487148857</TimeTick>
<NodeArgs eType="Replay" icon="43" nRep="18" >
<Disp><![CDATA[System i signon.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="43" nRep="16" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[System i signon]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:17]]></Time>
<TimeTick>1487148857</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["InfoProWindow"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:17]]></Time>
<TimeTick>1487148857</TimeTick>
<NodeArgs eType="Replay" icon="45" nRep="20" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA["InfoProWindow"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["InfoProWindow"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>terminal emulator=Yes<br>short name=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:17]]></Time>
<TimeTick>1487148857</TimeTick>
<NodeArgs eType="Replay" icon="46" nRep="21" Source="Action1" SourceLine="-1" >
<Disp><![CDATA["InfoProWindow"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:20]]></Time>
<TimeTick>1487148860</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[UserId.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:20]]></Time>
<TimeTick>1487148860</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="24" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[UserId.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[  [24 x 80] ].Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:20]]></Time>
<TimeTick>1487148860</TimeTick>
<NodeArgs eType="Replay" icon="49" nRep="26" >
<Disp><![CDATA[[  [24 x 80] ].Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[UserId.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:20]]></Time>
<TimeTick>1487148860</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="27" >
<Disp><![CDATA[UserId.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:20]]></Time>
<TimeTick>1487148860</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="28" >
<Disp><![CDATA[Password.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[UserId.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["darapch"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:20]]></Time>
<TimeTick>1487148860</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="30" >
<Disp><![CDATA[UserId.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="23" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="45" nRep="19" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Enter UserId in the Login Screen]]></Obj>
<Details ><![CDATA[The value 'darapch' entered into the field UserId]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:22]]></Time>
<TimeTick>1487148862</TimeTick>
<NodeArgs eType="User" icon="42" nRep="31" status="Passed" >
<Disp><![CDATA[Enter UserId in the Login Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:22]]></Time>
<TimeTick>1487148862</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:22]]></Time>
<TimeTick>1487148862</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Sachin8187"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:22]]></Time>
<TimeTick>1487148862</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="35" >
<Disp><![CDATA[Password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="34" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:26]]></Time>
<TimeTick>1487148866</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ screen10365 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:26]]></Time>
<TimeTick>1487148866</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="38" >
<Disp><![CDATA[[ screen10365 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ TeScreen ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:26]]></Time>
<TimeTick>1487148866</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="39" >
<Disp><![CDATA[[ TeScreen ].Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="37" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Menu]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:28]]></Time>
<TimeTick>1487148868</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[InfoPro.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:28]]></Time>
<TimeTick>1487148868</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="43" >
<Disp><![CDATA[InfoPro.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="42" >
<Disp><![CDATA[Menu]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="45" nRep="33" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[Enter InfoPro in the Menu Screen]]></Obj>
<Details ><![CDATA[The value '1' entered into the field InfoPro]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:28]]></Time>
<TimeTick>1487148868</TimeTick>
<NodeArgs eType="User" icon="42" nRep="44" status="Passed" >
<Disp><![CDATA[Enter InfoPro in the Menu Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:29]]></Time>
<TimeTick>1487148869</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:29]]></Time>
<TimeTick>1487148869</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:29]]></Time>
<TimeTick>1487148869</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="48" >
<Disp><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ TeScreen ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:29]]></Time>
<TimeTick>1487148869</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="49" >
<Disp><![CDATA[[ TeScreen ].Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="47" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="45" nRep="46" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[Database connection]]></Obj>
<Details ><![CDATA[Database connection sucess]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:33]]></Time>
<TimeTick>1487148873</TimeTick>
<NodeArgs eType="User" icon="42" nRep="51" status="Passed" >
<Disp><![CDATA[Database connection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[DB query Execution Passed]]></Obj>
<Details ><![CDATA[SELECT * FROM cufile.CUPAAPRO WHERE pvarchar2 = 'B75533']]></Details>
<Time><![CDATA[2/15/2017 - 14:24:34]]></Time>
<TimeTick>1487148874</TimeTick>
<NodeArgs eType="User" icon="42" nRep="52" status="Passed" >
<Disp><![CDATA[DB query Execution Passed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[QUOTE NUMBER : ]]></Obj>
<Details ><![CDATA[B75533]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:35]]></Time>
<TimeTick>1487148875</TimeTick>
<NodeArgs eType="User" icon="42" nRep="53" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[QUOTE NUMBER : ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Database connection]]></Obj>
<Details ><![CDATA[Database connection sucess]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:38]]></Time>
<TimeTick>1487148878</TimeTick>
<NodeArgs eType="User" icon="42" nRep="54" status="Passed" >
<Disp><![CDATA[Database connection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[DB query Execution Passed]]></Obj>
<Details ><![CDATA[Select * from cufile.BIPIC where ICCOMP = '  847']]></Details>
<Time><![CDATA[2/15/2017 - 14:24:39]]></Time>
<TimeTick>1487148879</TimeTick>
<NodeArgs eType="User" icon="42" nRep="55" status="Passed" >
<Disp><![CDATA[DB query Execution Passed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:40]]></Time>
<TimeTick>1487148880</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Region]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:40]]></Time>
<TimeTick>1487148880</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Region.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:40]]></Time>
<TimeTick>1487148880</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="58" >
<Disp><![CDATA[Region.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Region.SetCursorPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:40]]></Time>
<TimeTick>1487148880</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="60" >
<Disp><![CDATA[Region.SetCursorPos]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="57" >
<Disp><![CDATA[Region]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:40]]></Time>
<TimeTick>1487148880</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_BACKTAB"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:40]]></Time>
<TimeTick>1487148880</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="63" >
<Disp><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:40]]></Time>
<TimeTick>1487148880</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="65" >
<Disp><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:43]]></Time>
<TimeTick>1487148883</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="67" >
<Disp><![CDATA[[ Systems Utilities Archiv ].SendKey]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="62" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="45" nRep="56" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Region Selected sucessfully]]></Obj>
<Details ><![CDATA[The Selected Region : BIDBFE]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:43]]></Time>
<TimeTick>1487148883</TimeTick>
<NodeArgs eType="User" icon="42" nRep="68" status="Passed" >
<Disp><![CDATA[Region Selected sucessfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:44]]></Time>
<TimeTick>1487148884</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Division]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:44]]></Time>
<TimeTick>1487148884</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Division.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:44]]></Time>
<TimeTick>1487148884</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="72" >
<Disp><![CDATA[Division.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Division.SetCursorPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:44]]></Time>
<TimeTick>1487148884</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="74" >
<Disp><![CDATA[Division.SetCursorPos]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="71" >
<Disp><![CDATA[Division]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:44]]></Time>
<TimeTick>1487148884</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ 2/15/17 1:54:44 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_BACKTAB"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:44]]></Time>
<TimeTick>1487148884</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="77" >
<Disp><![CDATA[[ 2/15/17 1:54:44 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ 2/15/17 1:54:44 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:44]]></Time>
<TimeTick>1487148884</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="79" >
<Disp><![CDATA[[ 2/15/17 1:54:44 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ 2/15/17 1:54:44 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:47]]></Time>
<TimeTick>1487148887</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="81" >
<Disp><![CDATA[[ 2/15/17 1:54:44 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="76" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="45" nRep="70" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[Division Selected sucessfully]]></Obj>
<Details ><![CDATA[The Selected Division : 847]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:47]]></Time>
<TimeTick>1487148887</TimeTick>
<NodeArgs eType="User" icon="42" nRep="82" status="Passed" >
<Disp><![CDATA[Division Selected sucessfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:52]]></Time>
<TimeTick>1487148892</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[PrimaryMenu]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:52]]></Time>
<TimeTick>1487148892</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[EODJobs.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:52]]></Time>
<TimeTick>1487148892</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="87" >
<Disp><![CDATA[EODJobs.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="86" >
<Disp><![CDATA[PrimaryMenu]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:52]]></Time>
<TimeTick>1487148892</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ 2/15/17 1:54:47 MIS SCO ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:52]]></Time>
<TimeTick>1487148892</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="90" >
<Disp><![CDATA[[ 2/15/17 1:54:47 MIS SCO ].SendKey]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="89" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[PrimaryMenu]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:52]]></Time>
<TimeTick>1487148892</TimeTick>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[EODJobs.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:52]]></Time>
<TimeTick>1487148892</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="92" >
<Disp><![CDATA[EODJobs.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[EODJobs.SetCursorPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:52]]></Time>
<TimeTick>1487148892</TimeTick>
<NodeArgs eType="Replay" icon="48" nRep="94" >
<Disp><![CDATA[EODJobs.SetCursorPos]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="91" >
<Disp><![CDATA[PrimaryMenu]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:53]]></Time>
<TimeTick>1487148893</TimeTick>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ 2/15/17 1:54:47 MIS SCO ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_BACKTAB"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:53]]></Time>
<TimeTick>1487148893</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="97" >
<Disp><![CDATA[[ 2/15/17 1:54:47 MIS SCO ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ 2/15/17 1:54:47 MIS SCO ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:53]]></Time>
<TimeTick>1487148893</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="99" >
<Disp><![CDATA[[ 2/15/17 1:54:47 MIS SCO ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ 2/15/17 1:54:47 MIS SCO ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:56]]></Time>
<TimeTick>1487148896</TimeTick>
<NodeArgs eType="Replay" icon="47" nRep="101" >
<Disp><![CDATA[[ 2/15/17 1:54:47 MIS SCO ].SendKey]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="47" nRep="96" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="45" nRep="85" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj ><![CDATA[Primary Selection Selected sucessfully]]></Obj>
<Details ><![CDATA[EODJobs is selected @ 'Primary Selection']]></Details>
<Time><![CDATA[2/15/2017 - 14:24:56]]></Time>
<TimeTick>1487148896</TimeTick>
<NodeArgs eType="User" icon="42" nRep="102" status="Passed" >
<Disp><![CDATA[Primary Selection Selected sucessfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:56]]></Time>
<TimeTick>1487148896</TimeTick>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[EODJobs]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/15/2017 - 14:24:56]]></Time>
<TimeTick>1487148896</TimeTick>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[EODDispatch.Exist]]></Obj>