<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="PBNHMRY"><DocLocation><![CDATA[C:\Users\darapch\Desktop\InfoPro_Residence_Just Hold For a While\TestScript\BIDIV216_SELECT ADJUSTMENTS FOR POSTING]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[BIDIV216_SELECT ADJUSTMENTS FOR POSTING]]></DName>
<Res><![CDATA[Res14]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:55]]></Time>
<TimeTick>1487683435</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[BIDIV216_SelectAdjustmentsForPosting]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:55]]></Time>
<TimeTick>1487683435</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[SELECT ADJUSTMENTS FOR POSTING.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:55]]></Time>
<TimeTick>1487683435</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SELECT ADJUSTMENTS FOR POSTING.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="9" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[BIDIV216_SelectAdjustmentsForPosting]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="8" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Verify 'SELECT ADJUSTMENTS FOR POSTING' Screen]]></Obj>
<Details ><![CDATA[The 'SELECT ADJUSTMENTS FOR POSTING' Screen is available]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:55]]></Time>
<TimeTick>1487683435</TimeTick>
<NodeArgs eType="User" icon="8" nRep="11" status="Passed" >
<Disp><![CDATA[Verify 'SELECT ADJUSTMENTS FOR POSTING' Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:56]]></Time>
<TimeTick>1487683436</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:56]]></Time>
<TimeTick>1487683436</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:56]]></Time>
<TimeTick>1487683436</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:57]]></Time>
<TimeTick>1487683437</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:57]]></Time>
<TimeTick>1487683437</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:57]]></Time>
<TimeTick>1487683437</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:58]]></Time>
<TimeTick>1487683438</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:58]]></Time>
<TimeTick>1487683438</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="24" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:58]]></Time>
<TimeTick>1487683438</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="25" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:58]]></Time>
<TimeTick>1487683438</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:59]]></Time>
<TimeTick>1487683439</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:59]]></Time>
<TimeTick>1487683439</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="31" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:59]]></Time>
<TimeTick>1487683439</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:53:59]]></Time>
<TimeTick>1487683439</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="34" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:00]]></Time>
<TimeTick>1487683440</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:01]]></Time>
<TimeTick>1487683441</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:01]]></Time>
<TimeTick>1487683441</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:01]]></Time>
<TimeTick>1487683441</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="41" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:02]]></Time>
<TimeTick>1487683442</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:02]]></Time>
<TimeTick>1487683442</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="45" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:02]]></Time>
<TimeTick>1487683442</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="46" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:02]]></Time>
<TimeTick>1487683442</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="48" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:03]]></Time>
<TimeTick>1487683443</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="50" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:03]]></Time>
<TimeTick>1487683443</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:03]]></Time>
<TimeTick>1487683443</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="53" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:03]]></Time>
<TimeTick>1487683443</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:04]]></Time>
<TimeTick>1487683444</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="57" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:05]]></Time>
<TimeTick>1487683445</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="59" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:05]]></Time>
<TimeTick>1487683445</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="60" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:05]]></Time>
<TimeTick>1487683445</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="62" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:06]]></Time>
<TimeTick>1487683446</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="64" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:06]]></Time>
<TimeTick>1487683446</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="66" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:06]]></Time>
<TimeTick>1487683446</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="67" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:06]]></Time>
<TimeTick>1487683446</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="69" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:07]]></Time>
<TimeTick>1487683447</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="71" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:07]]></Time>
<TimeTick>1487683447</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="73" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:07]]></Time>
<TimeTick>1487683447</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="74" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:07]]></Time>
<TimeTick>1487683447</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="76" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:08]]></Time>
<TimeTick>1487683448</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="78" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:08]]></Time>
<TimeTick>1487683448</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="80" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:09]]></Time>
<TimeTick>1487683449</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="81" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:09]]></Time>
<TimeTick>1487683449</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="83" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:10]]></Time>
<TimeTick>1487683450</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="85" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:10]]></Time>
<TimeTick>1487683450</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="87" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:10]]></Time>
<TimeTick>1487683450</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="88" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:10]]></Time>
<TimeTick>1487683450</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="90" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:11]]></Time>
<TimeTick>1487683451</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="92" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:11]]></Time>
<TimeTick>1487683451</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="94" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:11]]></Time>
<TimeTick>1487683451</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="95" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:11]]></Time>
<TimeTick>1487683451</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="97" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:12]]></Time>
<TimeTick>1487683452</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="99" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:12]]></Time>
<TimeTick>1487683452</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="101" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:13]]></Time>
<TimeTick>1487683453</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="102" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:13]]></Time>
<TimeTick>1487683453</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="104" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:14]]></Time>
<TimeTick>1487683454</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="106" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ TeField ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:14]]></Time>
<TimeTick>1487683454</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="108" >
<Disp><![CDATA[[ TeField ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ field1679(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:14]]></Time>
<TimeTick>1487683454</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="109" >
<Disp><![CDATA[[ field1679(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PAGE_DOWN"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:14]]></Time>
<TimeTick>1487683454</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="111" >
<Disp><![CDATA[[ 2/21/17 Company 050 SEL ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ 196196(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:15]]></Time>
<TimeTick>1487683455</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="112" >
<Disp><![CDATA[[ 196196(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ 196196(protected) ].SetCursorPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[2/21/2017 - 18:54:15]]></Time>
<TimeTick>1487683455</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="114" >
<Disp><![CDATA[[ 196196(protected) ].SetCursorPos]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="13" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2/21/2017 - 18:53:55" eTime="2/21/2017 - 18:54:22" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[BIDIV216_SELECT ADJUSTMENTS FOR POSTING Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2/21/2017 - 18:53:54" eTime="2/21/2017 - 18:54:22" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test BIDIV216_SELECT ADJUSTMENTS FOR POSTING Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>