<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="PBNHMRY"><DocLocation><![CDATA[C:\Users\darapch\Desktop\InfoPro_Residence_Modifications\TestScript\BIGDS031_ServiceRecording]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[BIGDS031_ServiceRecording]]></DName>
<Res><![CDATA[Res29]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[BIGDS031_SERVICE RECORDING]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[ServicingRecording.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ServicingRecording.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="9" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[BIGDS031_SERVICE RECORDING]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="8" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Verify the 'Service Recording' Screen]]></Obj>
<Details ><![CDATA[The 'Service Recording' screen is Available]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<NodeArgs eType="User" icon="8" nRep="11" status="Passed" >
<Disp><![CDATA[Verify the 'Service Recording' Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ 34728(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" >
<Disp><![CDATA[[ 34728(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="12" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Verify the Serv # '34728']]></Obj>
<Details ><![CDATA[The Serv # '34728' is Available]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<NodeArgs eType="User" icon="8" nRep="15" status="Passed" >
<Disp><![CDATA[Verify the Serv # '34728']]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Verify the Status]]></Obj>
<Details ><![CDATA[The Status for the Serv# '34728' is '']]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<NodeArgs eType="User" icon="8" nRep="16" status="Passed" >
<Disp><![CDATA[Verify the Status]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[BIGDS031_SERVICE RECORDING]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ field482 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ field482 ].Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="19" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[BIGDS031_SERVICE RECORDING]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" >
<Disp><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ TeScreen ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/3/2017 - 15:31:58]]></Time>
<TimeTick>1488535318</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" >
<Disp><![CDATA[[ TeScreen ].Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="22" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[The Available Code]]></Obj>
<Details ><![CDATA[The Available Code : ADCM]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:00]]></Time>
<TimeTick>1488535320</TimeTick>
<NodeArgs eType="User" icon="8" nRep="26" >
<Disp><![CDATA[The Available Code]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:00]]></Time>
<TimeTick>1488535320</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[BIGDS031_SERVICE RECORDING]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:00]]></Time>
<TimeTick>1488535320</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Code.SetCursorPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:00]]></Time>
<TimeTick>1488535320</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Code.SetCursorPos]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="29" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[BIGDS031_SERVICE RECORDING]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:00]]></Time>
<TimeTick>1488535320</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PF4"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:00]]></Time>
<TimeTick>1488535320</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" >
<Disp><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ ADCM(protected) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:02]]></Time>
<TimeTick>1488535322</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" >
<Disp><![CDATA[[ ADCM(protected) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ 3/03/17 03:02:00 T ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PF3"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:02]]></Time>
<TimeTick>1488535322</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="36" >
<Disp><![CDATA[[ 3/03/17 03:02:00 T ].SendKey]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="32" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[BIGDS031_SERVICE RECORDING]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:02]]></Time>
<TimeTick>1488535322</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Subject.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SUBJECT-MAR-3-15-32-2"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:02]]></Time>
<TimeTick>1488535322</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" >
<Disp><![CDATA[Subject.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="38" >
<Disp><![CDATA[BIGDS031_SERVICE RECORDING]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="28" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Enter Subject in the BIGDS031_SERVICE RECORDING Screen]]></Obj>
<Details ><![CDATA[The value 'SUBJECT-MAR-3-15-32-2' entered into the field Subject]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:02]]></Time>
<TimeTick>1488535322</TimeTick>
<NodeArgs eType="User" icon="8" nRep="40" status="Passed" >
<Disp><![CDATA[Enter Subject in the BIGDS031_SERVICE RECORDING Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:02]]></Time>
<TimeTick>1488535322</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[BIGDS031_SERVICE RECORDING]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:02]]></Time>
<TimeTick>1488535322</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[ServiceText.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Service Text - Mar-3-15-32-2"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:02]]></Time>
<TimeTick>1488535322</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="44" >
<Disp><![CDATA[ServiceText.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="43" >
<Disp><![CDATA[BIGDS031_SERVICE RECORDING]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="42" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Enter ServiceText in the BIGDS031_SERVICE RECORDING Screen]]></Obj>
<Details ><![CDATA[The value 'Service Text - Mar-3-15-32-2' entered into the field ServiceText]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:03]]></Time>
<TimeTick>1488535323</TimeTick>
<NodeArgs eType="User" icon="8" nRep="45" status="Passed" >
<Disp><![CDATA[Enter ServiceText in the BIGDS031_SERVICE RECORDING Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The environment parameter &quot;Route&quot; was not found. Confirm that an environment parameter with this name is defined or specify another environment variable.<BR/>Line (170): &quot;Call func_EnterValueInTeField(&quot;BIGDS031_SERVICE RECORDING&quot;,&quot;Route&quot;,Environment.Value(&quot;Route&quot;))&quot;. ]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:03]]></Time>
<TimeTick>1488535323</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" status="Failed" Source="Action1" SourceLine="169" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The environment parameter &quot;Truck&quot; was not found. Confirm that an environment parameter with this name is defined or specify another environment variable.<BR/>Line (172): &quot;Call func_EnterValueInTeField(&quot;BIGDS031_SERVICE RECORDING&quot;,&quot;Truck&quot;,Environment.Value(&quot;Truck&quot;))&quot;. ]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:06]]></Time>
<TimeTick>1488535326</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" status="Failed" Source="Action1" SourceLine="171" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The environment parameter &quot;Employee&quot; was not found. Confirm that an environment parameter with this name is defined or specify another environment variable.<BR/>Line (173): &quot;Call func_EnterValueInTeField(&quot;BIGDS031_SERVICE RECORDING&quot;,&quot;Employee&quot;,Environment.Value(&quot;Employee&quot;))&quot;. ]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:07]]></Time>
<TimeTick>1488535327</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="48" status="Failed" Source="Action1" SourceLine="172" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[BIGDS031_SERVICE RECORDING]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[ScheduledCompletionMonth.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[" 3"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" >
<Disp><![CDATA[ScheduledCompletionMonth.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="51" >
<Disp><![CDATA[BIGDS031_SERVICE RECORDING]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="50" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Enter ScheduledCompletionMonth in the BIGDS031_SERVICE RECORDING Screen]]></Obj>
<Details ><![CDATA[The value ' 3' entered into the field ScheduledCompletionMonth]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="User" icon="8" nRep="53" status="Passed" >
<Disp><![CDATA[Enter ScheduledCompletionMonth in the BIGDS031_SERVICE RECORDING Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[BIGDS031_SERVICE RECORDING]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[ScheduledCompletionDate.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[" 3"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="57" >
<Disp><![CDATA[ScheduledCompletionDate.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="56" >
<Disp><![CDATA[BIGDS031_SERVICE RECORDING]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="55" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Enter ScheduledCompletionDate in the BIGDS031_SERVICE RECORDING Screen]]></Obj>
<Details ><![CDATA[The value ' 3' entered into the field ScheduledCompletionDate]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="User" icon="8" nRep="58" status="Passed" >
<Disp><![CDATA[Enter ScheduledCompletionDate in the BIGDS031_SERVICE RECORDING Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[BIGDS031_SERVICE RECORDING]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[ScheduledCompletionYear.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["17"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="62" >
<Disp><![CDATA[ScheduledCompletionYear.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="61" >
<Disp><![CDATA[BIGDS031_SERVICE RECORDING]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="60" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Enter ScheduledCompletionYear in the BIGDS031_SERVICE RECORDING Screen]]></Obj>
<Details ><![CDATA[The value '17' entered into the field ScheduledCompletionYear]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="User" icon="8" nRep="63" status="Passed" >
<Disp><![CDATA[Enter ScheduledCompletionYear in the BIGDS031_SERVICE RECORDING Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_PF10"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="67" >
<Disp><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="66" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[BIGDS031_SERVICE RECORDING]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[ActionTaken.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Update the Serv# 34728 - 3/3/2017"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="70" >
<Disp><![CDATA[ActionTaken.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="69" >
<Disp><![CDATA[BIGDS031_SERVICE RECORDING]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="65" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj ><![CDATA[Enter ActionTaken in the BIGDS031_SERVICE RECORDING Screen]]></Obj>
<Details ><![CDATA[The value 'Update the Serv# 34728 - 3/3/2017' entered into the field ActionTaken]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="User" icon="8" nRep="71" status="Passed" >
<Disp><![CDATA[Enter ActionTaken in the BIGDS031_SERVICE RECORDING Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[InfoProWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Obj>
<Details plainTxt="False" ><![CDATA["TE_ENTER"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="75" >
<Disp><![CDATA[[ 3/03/17 Company 902 ].SendKey]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ TeScreen ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:08]]></Time>
<TimeTick>1488535328</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="76" >
<Disp><![CDATA[[ TeScreen ].Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="74" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[BIGDS031_SERVICE RECORDING]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:10]]></Time>
<TimeTick>1488535330</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[GridHeader.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:10]]></Time>
<TimeTick>1488535330</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="79" Source="Action1" SourceLine="172" >
<Disp><![CDATA[GridHeader.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="78" Source="Action1" SourceLine="172" >
<Disp><![CDATA[BIGDS031_SERVICE RECORDING]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="73" >
<Disp><![CDATA[InfoProWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[Press Enter]]></Obj>
<Details ><![CDATA[Information is updated and user is exit back to 'Service Recording' screen]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:10]]></Time>
<TimeTick>1488535330</TimeTick>
<NodeArgs eType="User" icon="8" nRep="80" status="Passed" >
<Disp><![CDATA[Press Enter]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA[Verify Record Existancy for the Trigger Table BIPSUO]]></Obj>
<Details ><![CDATA[Atleast 1 Record is available for BIPSUO]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:16]]></Time>
<TimeTick>1488535336</TimeTick>
<NodeArgs eType="User" icon="8" nRep="81" status="Passed" >
<Disp><![CDATA[Verify Record Existancy for the Trigger Table BIPSUO]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj ><![CDATA[Verify Transaction_Code column]]></Obj>
<Details ><![CDATA[The Value of the column 'TRANSACTION_CODE' in DB is 'ADCM' and matched with the Code provided in service recording]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:16]]></Time>
<TimeTick>1488535336</TimeTick>
<NodeArgs eType="User" icon="8" nRep="82" status="Passed" >
<Disp><![CDATA[Verify Transaction_Code column]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj ><![CDATA[Verify 'SCHEDULED_COMPLETION_DATE' column]]></Obj>
<Details ><![CDATA[The value of 'SCHEDULED_COMPLETION_DATE' in DB is '3/3/2017. Mathced with the provided Scheduled time in service recording]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:16]]></Time>
<TimeTick>1488535336</TimeTick>
<NodeArgs eType="User" icon="8" nRep="83" status="Passed" >
<Disp><![CDATA[Verify 'SCHEDULED_COMPLETION_DATE' column]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA[Verify the 'Text _Description' column in BIPSUO Record]]></Obj>
<Details ><![CDATA[The Value of the column 'Text_Description' in DB is ''. The Service Text provided in service recording screen is '']]></Details>
<Time><![CDATA[3/3/2017 - 15:32:16]]></Time>
<TimeTick>1488535336</TimeTick>
<NodeArgs eType="User" icon="8" nRep="84" status="Passed" >
<Disp><![CDATA[Verify the 'Text _Description' column in BIPSUO Record]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj ><![CDATA[Verify Record Existancy for the Trigger Table BIPSX]]></Obj>
<Details ><![CDATA[Atleast 1 Record is available for BIPSX]]></Details>
<Time><![CDATA[3/3/2017 - 15:32:20]]></Time>
<TimeTick>1488535340</TimeTick>
<NodeArgs eType="User" icon="8" nRep="85" status="Passed" >
<Disp><![CDATA[Verify Record Existancy for the Trigger Table BIPSX]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj ><![CDATA[Verify data in F10_Text_Description column]]></Obj>
<Details ><![CDATA[The Value of the column 'F10_Text_Description' in DB is 'Update the Serv# 34728 - 3/3/2017'. The Action Taken text provided is 'Update the Serv# 34728 - 3/3/2017']]></Details>
<Time><![CDATA[3/3/2017 - 15:32:20]]></Time>
<TimeTick>1488535340</TimeTick>
<NodeArgs eType="User" icon="8" nRep="86" status="Passed" >
<Disp><![CDATA[Verify data in F10_Text_Description column]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/3/2017 - 15:31:58" eTime="3/3/2017 - 15:32:20" passed="16" failed="3" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[BIGDS031_ServiceRecording Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="3/3/2017 - 15:31:57" eTime="3/3/2017 - 15:32:20" passed="16" failed="3" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >